### ISSUE TITLE
Quote strings

### ISSUE THREAD

**Issue by KittyGiraudel** [jakecleary/elf-scss#10]
Aside from `left` and `right` which are rather positions than strings, it's best practice to quote strings in Sass to help figuring out what's going on.

I'm mostly thinking of `$direction` in `align` and the like.

**Comment by jakecleary** [comment]
Damn that's annoying. When I was initially porting it over I used quotes, but removed them as it seemed to evaluate the vars as `"varname"`, which I thought would cause issues. I'll put them back in.

**Comment by KittyGiraudel** [comment]
`"string" == string` in Sass.

Quotes can be annoying if you do this:

``` scss
$value: "left";

test {
  clear: $value;
}
```

...because it compiles as:

``` css
test {
  clear: "left";
}
```

Which is obviously invalid CSS. However note that the following works perfectly:

``` scss
$value: "left";

test {
  #{$value}: 0;
}
```
